### PR TITLE
Fix the copy issue

### PR DESCRIPTION
**Pull request by jcreamer898**
The done callback should be moved inside the render method after the file has been written.

### CODE REVIEW

**Comment by arobson** [comment]
You can't call done AND anvil.stopBuild together, that will cause the build to continue, think of "done" as a "please keep building call". Will the fix still work if you just remove the done calls from the catch blocks? Thanks for working on this, @jcreamer898 :money_with_wings:

**Comment by jcreamer898** [comment]
Yea it'll work. I'll fix it real fast.

On Friday, February 8, 2013, Alex Robson wrote:

> You can't call done AND anvil.stopBuild together, that will cause the
> build to continue, think of "done" as a "please keep building call". Will
> the fix still work if you just remove the done calls from the catch blocks?
> Thanks for working on this, @jcreamer898 https://github.com/jcreamer898:money:
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/anviljs/anvil.template/pull/4#issuecomment-13317140..

## 

---

_Jonathan Creamer http://jcreamerlive.com_
_615-392-0809_
- http://www.facebook.com/profile.php?id=38421291
  http://twitter.com/#!/jcreamer898
  http://www.linkedin.com/profile/edit?id=82666787
  http://www.google.com/profiles/matrixhasyou2k4
  http://www.myspace.com/matrixhasyou2k4
  *
- \* jcreamer898
  *
  *

**Comment by jcreamer898** [comment]
There ya go!

**Comment by arobson** [comment]
Thanks again! I really appreciate your help tracking that down.

**Pull request merged**
